### ISSUE TITLE
utf8 problem on Windows

### ISSUE THREAD

**Issue by polakluk** [klen/pylama#108]
In version 7.4.1., pylama cant open files containing utf-8 characters. When executed in --verbose mode, it points to file core.py:
```
Traceback (most recent call last):
  File "***\site-packages\pylama\core.py", line 42, in run
    with CodeContext(code, path) as ctx:
  File "***\site-packages\pylama\core.py", line 196, in __enter__
    self.code = self._file.read()
  File "***\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 835: character maps to <undefined>
```

This is caused by line 195 in core.py, because default encoding in Windows is not utf-8.
```
self._file = open(self.path, mode)
```

Changing the line to this fixes the issue.
```
self._file = open(self.path, mode, encoding='utf-8')
```

**Comment by klen** [comment]
@polakluk Hello, fixed in version > 7.4.2
