### ISSUE TITLE
pylama crashes if pyflakes version < 0.9.0

### ISSUE THREAD

**Issue by luzfcb** [klen/pylama#42]
```
(django_documentos)luzfcb@oficina:~/projetos/opensource/django_documentos$ pip install pylama
Collecting pylama
  Downloading pylama-7.0.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): mccabe in /home/luzfcb/virtualenvs/django_documentos/lib/python2.7/site-packages (from pylama)
Requirement already satisfied (use --upgrade to upgrade): pep8 in /home/luzfcb/virtualenvs/django_documentos/lib/python2.7/site-packages (from pylama)
Requirement already satisfied (use --upgrade to upgrade): pyflakes in /home/luzfcb/virtualenvs/django_documentos/lib/python2.7/site-packages (from pylama)
Collecting pep257 (from pylama)
  Downloading pep257-0.6.0.tar.gz
Building wheels for collected packages: pep257
  Running setup.py bdist_wheel for pep257
  Stored in directory: /home/luzfcb/.cache/pip/wheels/3b/cc/26/9dc89894b5852b3ee7335b2eb61e46cbeebac52504555ec4af
Successfully built pep257
Installing collected packages: pep257, pylama
Successfully installed pep257-0.6.0 pylama-7.0.0

(django_documentos)luzfcb@oficina:~/projetos/opensource/django_documentos$ pylama --version
Traceback (most recent call last):
  File "/home/luzfcb/virtualenvs/django_documentos/bin/pylama", line 7, in <module>
    from pylama.main import shell
  File "/home/luzfcb/virtualenvs/django_documentos/local/lib/python2.7/site-packages/pylama/main.py", line 8, in <module>
    from .config import parse_options, CURDIR, setup_logger
  File "/home/luzfcb/virtualenvs/django_documentos/local/lib/python2.7/site-packages/pylama/config.py", line 12, in <module>
    from .lint.extensions import LINTERS
  File "/home/luzfcb/virtualenvs/django_documentos/local/lib/python2.7/site-packages/pylama/lint/extensions.py", line 24, in <module>
    from pylama.lint.pylama_pyflakes import Linter
  File "/home/luzfcb/virtualenvs/django_documentos/local/lib/python2.7/site-packages/pylama/lint/pylama_pyflakes.py", line 21, in <module>
    checker.messages.ReturnOutsideFunction.message = "E0104 'return' outside function"
AttributeError: 'module' object has no attribute 'ReturnOutsideFunction'


(django_documentos)luzfcb@oficina:~/projetos/opensource/django_documentos$ pip install pylama -U
Requirement already up-to-date: pylama in /home/luzfcb/virtualenvs/django_documentos/lib/python2.7/site-packages
Requirement already up-to-date: mccabe in /home/luzfcb/virtualenvs/django_documentos/lib/python2.7/site-packages (from pylama)
Requirement already up-to-date: pep8 in /home/luzfcb/virtualenvs/django_documentos/lib/python2.7/site-packages (from pylama)
Collecting pyflakes (from pylama)
  Downloading pyflakes-0.9.2-py2.py3-none-any.whl
Requirement already up-to-date: pep257 in /home/luzfcb/virtualenvs/django_documentos/lib/python2.7/site-packages (from pylama)
Installing collected packages: pyflakes
  Found existing installation: pyflakes 0.8.1
    Uninstalling pyflakes-0.8.1:
      Successfully uninstalled pyflakes-0.8.1
Successfully installed pyflakes-0.9.2
(django_documentos)luzfcb@oficina:~/projetos/opensource/django_documentos$ pylama django_documentos tests

```

**Comment by klen** [comment]
Thank you for the feedback.
