### ISSUE TITLE
pylama doesn't work with latest version of pylint

### ISSUE THREAD

**Issue by osman-masood** [klen/pylama#54]
When I run pylama with the latest version of pylint (1.5.4 but also tried 1.5.0), I get a `VersionConflict` exception.  It doesn't happen when pylint is on an older version, 1.4.4.  

```
oamasood@Osmans-MacBook-Pro:~/src/my-project$ pylama my_app/
Traceback (most recent call last):
  File "/Users/oamasood/.pyenv/versions/2.7.9/bin/pylama", line 7, in <module>
    from pylama.main import shell
  File "/Users/oamasood/.pyenv/versions/2.7.9/lib/python2.7/site-packages/pylama/main.py", line 8, in <module>
    from .config import parse_options, CURDIR, setup_logger
  File "/Users/oamasood/.pyenv/versions/2.7.9/lib/python2.7/site-packages/pylama/config.py", line 12, in <module>
    from .lint.extensions import LINTERS
  File "/Users/oamasood/.pyenv/versions/2.7.9/lib/python2.7/site-packages/pylama/lint/extensions.py", line 35, in <module>
    LINTERS[entry.name] = entry.load()()
  File "/Users/oamasood/.pyenv/versions/2.7.9/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2354, in load
    self.require(*args, **kwargs)
  File "/Users/oamasood/.pyenv/versions/2.7.9/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2371, in require
    items = working_set.resolve(reqs, env, installer)
  File "/Users/oamasood/.pyenv/versions/2.7.9/lib/python2.7/site-packages/pkg_resources/__init__.py", line 844, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.VersionConflict: (pylint 1.5.4 (/Users/oamasood/.pyenv/versions/2.7.9/lib/python2.7/site-packages), Requirement.parse('pylint==1.4.4'))
```

Setting `--verbose` doesn't give any additional input. Here's my `tox.ini` config:

``` ini

[pylama]
skip = */.tox/*,*/.env/*,dashboard/*
linters = pylint,pep8,mccabe
format = pylint

[pylama:pep8]
max_line_length = 119

[pylama:pylint]
max_line_length = 119

[pylama:mccabe]
max-complexity = 10
```

When the pylint version is 1.4.4, it still gives me some errors on output, but it works:

```
Try to read configuration from: 
Namespace(abspath=False, async=False, file_params={}, force=False, format='pylint', hook=False, ignore=[], linters=[('pep8', <pylama.lint.pylama_pep8.Linter object at 0x107142d50>), ('pylint', <pylama_pylint.main.Linter object at 0x1074eef50>), ('mccabe', <pylama.lint.pylama_mccabe.Linter object at 0x106fa4390>)], linters_params={u'pep8': {u'max_line_length': 119}, u'pylint': {u'max_line_length': 119}, u'mccabe': {u'max-complexity': 10}}, options='', paths=['my_app'], report=None, select=[], skip=[<_sre.SRE_Pattern object at 0x1079ac618>, <_sre.SRE_Pattern object at 0x1079ac8a0>, <_sre.SRE_Pattern object at 0x1079aa8b8>], sort=[], verbose=True)
File is reading: my_app/__init__.py
Run pep8 {u'max_line_length': 119}
Run pylint {u'max_line_length': 119}
Problem importing module classes.py: cannot import name InferenceContext
Problem importing module classes.pyc: cannot import name InferenceContext
Run mccabe {u'max-complexity': 10}
```

Any help would be appreciated... Thanks!
##

**Comment by osman-masood** [comment]
This might help:

https://bitbucket.org/logilab/pylint/issues/720/problem-importing-module-classespy-cannot

Seems like pylint 1.5.0 fixes this problem.  However, seems like pylama is dependent upon version 1.4.4 of pylint.

**Comment by diefans** [comment]
I guess you have two versions of pylama installed where one has pinned pylint to 1.4.4.
Try to clean your env...

**Comment by mzfr** [comment]
@osman-masood Is this issue fixed ?

**Comment by klen** [comment]
Thank you for the feedback. The issue has been fixed.
