### ISSUE TITLE
PyFlakes 1.1.0 support?

### ISSUE THREAD

**Issue by jsivak** [klen/pylama#57]
PyFlakes 1.1.0 is out and Pylama is throwing the following error:

```
Traceback (most recent call last):
  File "/home/jsivak/projects/beat_matrix_checker_ve/bin/pylama", line 7, in <module>
    from pylama.main import shell
  File "/home/jsivak/projects/beat_matrix_checker_ve/lib/python2.7/site-packages/pylama/main.py", line 8, in <module>
    from .config import parse_options, CURDIR, setup_logger
  File "/home/jsivak/projects/beat_matrix_checker_ve/lib/python2.7/site-packages/pylama/config.py", line 12, in <module>
    from .lint.extensions import LINTERS
  File "/home/jsivak/projects/beat_matrix_checker_ve/lib/python2.7/site-packages/pylama/lint/extensions.py", line 35, in <module>
    LINTERS[entry.name] = entry.load()()
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2379, in load
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2396, in require
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 833, in resolve
pkg_resources.ContextualVersionConflict: (pyflakes 1.1.0 (/home/jsivak/projects/beat_matrix_checker_ve/lib/python2.7/site-packages), Requirement.parse('pyflakes==1.0.0'), set(['pylama']))
```

Not sure if the requirements for Pylama just need to be updated or if there is some testing that Pylama needs to do to support Pyflakes 1.1.0.

When I manually update the METADATA file in my virtualenv's lib/python2.7/site-packages/pylama-7.0.7.dist-info directory:
from:
`Requires-Dist: pyflakes (==1.0.0)`
to:
`Requires-Dist: pyflakes (>=1.0.0)`

everything seems to work.
##

**Comment by rasschaert** [comment]
Same here, edited /usr/lib/python3.5/site-packages/pylama-7.0.7-py3.5.egg-info/requires.txt and everything works again.

On a cursory note, I had the same issue with pylama_pylint which has a hard dependency on pylint 1.5.4 while 1.5.5 is out.

**Comment by roll** [comment]
:+1:
