### ISSUE TITLE
AttributeError: 'PylamaItem' object has no attribute '_fixtureinfo'

### ISSUE THREAD

**Issue by pwilczynskiclearcode** [klen/pylama#87]
```bash
pytest --fixtures-per-test --pylama
========================= test session starts ================================
platform linux2 -- Python 2.7.12, pytest-3.0.5, py-1.4.32, pluggy-0.4.0
Django settings: xyx.settings.test (from command line option)
rootdir: /opt/xyz, inifile: pytest.ini
plugins: django-3.1.2, cov-2.4.0, catchlog-1.2.2, pylama-7.3.3
collected 231 items 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/usr/local/lib/python2.7/site-packages/_pytest/main.py", line 98, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/usr/local/lib/python2.7/site-packages/_pytest/python.py", line 1031, in _show_fixtures_per_test
INTERNALERROR>     write_item(item)
INTERNALERROR>   File "/usr/local/lib/python2.7/site-packages/_pytest/python.py", line 1012, in write_item
INTERNALERROR>     name2fixturedefs = item._fixtureinfo.name2fixturedefs
INTERNALERROR> AttributeError: 'PylamaItem' object has no attribute '_fixtureinfo'

=========================1 tests deselected ===================================
==================== 1 deselected in 0.15 seconds =============================
```
```bash
$ pytest --version
This is pytest version 3.0.5, imported from /usr/local/lib/python2.7/site-packages/pytest.pyc
setuptools registered plugins:
  pytest-django-3.1.2 at /usr/local/lib/python2.7/site-packages/pytest_django/plugin.py
  pytest-cov-2.4.0 at /usr/local/lib/python2.7/site-packages/pytest_cov/plugin.py
  pytest-catchlog-1.2.2 at /usr/local/lib/python2.7/site-packages/pytest_catchlog.py
  pylama-7.3.3 at /usr/local/lib/python2.7/site-packages/pylama/pytest.py
```

**Comment by pwilczynskiclearcode** [comment]
The same happens on `pytest --setup-show`
